# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2024-2026 Eric Bintner and Halbert Contributors
# Repo-wide pytest floor. halbert_core/pyproject.toml remains the inifile for
# the halbert_core gate (a pyproject with [tool.pytest.ini_options] outranks
# a pytest.ini only when it is found FIRST walking up from the args — the
# package dir is deeper, so it still wins for `wt_pytest.py halbert_core/tests`).
# This file exists for every OTHER invocation shape: a run whose args span the
# repo root (e.g. `pytest tests halbert_core/tests`, or any pathspec whose
# common ancestor is the checkout root) resolves this as its inifile. Without
# it those runs get NO inifile, pytest-asyncio falls back to its built-in
# mode=strict default, and every bare `async def test_` in the voice/TTS/
# terminal-stream/compute suites fails with "async def functions are not
# natively supported" plus 17 async-fixture setup errors — a 205-failed gate
# signature that is pure invocation environment, not a code regression
# (diagnosed 2026-09-08 from /tmp/wave4_full_suite.log: header present,
# rootdir = worktree root, "asyncio: mode=strict").
# Only the asyncio contract lives here: no testpaths, no addopts — anything
# else would silently reshape suites that today resolve no inifile at all.
[pytest]
asyncio_mode = auto