#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2024-2026 Eric Bintner and Halbert Contributors
"""Derive the dashboard's shadcn theme slots from the canonical design tokens.

The dashboard is built on shadcn/ui, whose components read HSL triplets like
``--primary: 221.2 83.2% 53.3%`` and wrap them in ``hsl(var(--primary))``. The
Halbert dictionary in ``shared-tokens/tokens.css`` speaks hex and rgba. This
script is the bridge, and it exists so the mapping is *generated* rather than
hand-typed — a hand-typed copy is how this repo ended up with three divergent
palettes in the first place.

It rewrites the region between the BEGIN/END markers in the dashboard's
``index.css``. Everything outside those markers is left alone.

Usage::

    python3 scripts/gen_shadcn_theme.py           # rewrite index.css
    python3 scripts/gen_shadcn_theme.py --check   # fail if out of date
"""

from __future__ import annotations

import argparse
import colorsys
import re
import sys
from pathlib import Path

from check_contrast import (
    TOKENS_CSS,
    contrast_ratio,
    flatten,
    parse_blocks,
)

REPO_ROOT = Path(__file__).resolve().parent.parent
INDEX_CSS = (
    REPO_ROOT
    / "halbert_core/halbert_core/dashboard/frontend/src/index.css"
)

BEGIN = "  /* BEGIN generated by scripts/gen_shadcn_theme.py — do not edit by hand */"
END = "  /* END generated */"

# shadcn slot -> Halbert token.
#
# Two mappings are easy to get backwards and are called out here:
#   --accent      is shadcn's *hover/highlight background*, NOT the brand
#                 accent. Pointing it at vermilion would tint every menu
#                 hover, which is exactly the "vermilion as wallpaper" the
#                 brand rules forbid.
#   --primary     takes accent-STRONG, because --primary-foreground sits on
#                 top of it and the brand shade fails AA as a text-bearing fill.
SLOTS: dict[str, str] = {
    "background": "--color-canvas",
    "foreground": "--color-ink",
    "card": "--color-surface",
    "card-foreground": "--color-ink",
    "popover": "--color-surface",
    "popover-foreground": "--color-ink",
    "primary": "--color-accent-strong",
    "primary-foreground": "--color-ink-on-accent",
    "primary-muted": "--color-accent",
    "secondary": "--color-surface-subtle",
    "secondary-foreground": "--color-ink",
    "muted": "--color-surface-subtle",
    "muted-foreground": "--color-ink-tertiary",
    "accent": "--color-surface-subtle",
    "accent-foreground": "--color-ink",
    "destructive": "--color-status-critical",
    "destructive-foreground": "--color-ink-on-accent",
    "border": "--color-line",
    "input": "--color-line",
    "ring": "--color-focus-ring",
    # SourcePrep semantic tokens already present in this file.
    "surface": "--color-canvas",
    "surface-raised": "--color-surface",
    "text": "--color-ink",
    "text-muted": "--color-ink-tertiary",
    "text-subtle": "--color-ink-tertiary",
    "text-base": "--color-ink",
    "border-subtle": "--color-line-subtle",
    "success": "--color-status-nominal",
    "success-muted": "--color-status-nominal-bg",
    "error": "--color-status-critical",
    "error-muted": "--color-status-critical-bg",
    "warning": "--color-status-warning",
    "warning-muted": "--color-status-warning-bg",
    "info": "--color-status-telemetry",
    "info-muted": "--color-status-telemetry-bg",
}

# Pairs shadcn actually renders as text-on-ground, checked after conversion.
SLOT_CONTRAST_CHECKS: list[tuple[str, str, float]] = [
    ("foreground", "background", 7.0),
    ("foreground", "card", 7.0),
    ("card-foreground", "card", 7.0),
    ("popover-foreground", "popover", 7.0),
    ("muted-foreground", "background", 4.5),
    ("muted-foreground", "muted", 4.5),
    ("secondary-foreground", "secondary", 4.5),
    ("accent-foreground", "accent", 4.5),
    ("primary-foreground", "primary", 4.5),
    ("destructive-foreground", "destructive", 4.5),
    ("text-muted", "surface", 4.5),
    ("success", "surface", 4.5),
    ("warning", "surface", 4.5),
    ("error", "surface", 4.5),
    ("info", "surface", 4.5),
]


def to_hsl_triplet(rgb: tuple[int, int, int]) -> str:
    """Convert RGB to the space-separated ``H S% L%`` shadcn expects."""
    r, g, b = (c / 255 for c in rgb)
    h, l, s = colorsys.rgb_to_hls(r, g, b)
    return f"{round(h * 360, 1):g} {round(s * 100, 1):g}% {round(l * 100, 1):g}%"


def build_block(tokens: dict[str, str], indent: str) -> tuple[str, dict[str, tuple[int, int, int]]]:
    """Render the declaration block, and return the resolved RGB for checking."""
    ground = "--color-canvas"
    resolved: dict[str, tuple[int, int, int]] = {}
    lines: list[str] = []
    width = max(len(name) for name in SLOTS) + 4

    for slot, token in SLOTS.items():
        # Hairlines are translucent; shadcn needs an opaque triplet, so flatten
        # them onto the theme's own canvas rather than guessing a solid.
        rgb = flatten(token, tokens, ground)
        resolved[slot] = rgb
        decl = f"--{slot}:".ljust(width)
        lines.append(f"{indent}{decl}{to_hsl_triplet(rgb)};  /* {token.replace('--color-', '')} */")

    return "\n".join(lines), resolved


def check_slot_contrast(theme: str, resolved: dict[str, tuple[int, int, int]]) -> list[str]:
    failures = []
    for fg, bg, floor in SLOT_CONTRAST_CHECKS:
        ratio = contrast_ratio(resolved[fg], resolved[bg])
        if ratio < floor:
            failures.append(f"{theme}: --{fg} on --{bg} = {ratio:.2f}:1 (needs {floor}:1)")
    return failures


def render(light: dict[str, str], dark: dict[str, str]) -> tuple[str, list[str]]:
    light_block, light_rgb = build_block(light, "    ")
    dark_block, dark_rgb = build_block(dark, "      ")

    failures = check_slot_contrast("light", light_rgb) + check_slot_contrast("dark", dark_rgb)

    body = f"""{BEGIN}
  /*
   * Olivetti Vermilion & Bone, expressed as the HSL triplets shadcn/ui reads.
   * Source of truth: /shared-tokens/tokens.css. Regenerate with
   *   python3 scripts/gen_shadcn_theme.py
   * Every pair a shadcn component renders as text-on-ground is contrast-checked
   * at generation time, so this block cannot be regenerated into a failure.
   */
  :root {{
{light_block}
  }}

  .dark {{
{dark_block}
  }}
{END}"""
    return body, failures


TAILWIND_CONFIG = (
    REPO_ROOT / "halbert_core/halbert_core/dashboard/frontend/tailwind.config.js"
)

# Custom properties the config may reference that this script does not emit and
# tokens.css does not own: Tailwind/shadcn runtime vars and Radix measurements.
EXTERNAL_VARS = {
    "--tw-shadow", "--tw-ring-shadow", "--tw-inset-shadow",
    "--tw-ring-offset-shadow", "--tw-inset-ring-shadow",
    "--radix-accordion-content-height",
    "--sidepanel-width",
}


def check_dangling_vars() -> list[str]:
    """Every var() the Tailwind config reads must actually be defined.

    This exists because of a real regression: shadcn's `--radius` lived in the
    hand-written theme block that this script replaced, so it stopped being
    emitted. `var(--radius)` with no fallback is invalid at computed-value
    time, which meant every rounded-lg/md/sm surface in the app — Cards,
    Buttons, Inputs, Badges, Dialogs, Tabs — silently rendered SQUARE, while
    bare `rounded` and `rounded-full` kept rounding. Nothing failed; it just
    looked unfinished.
    """
    if not TAILWIND_CONFIG.exists():
        return []
    source = TAILWIND_CONFIG.read_text(encoding="utf-8")
    # Strip comments first: this file documents the very bug this guard exists
    # for, and prose mentioning `var(--radius)` is not a reference to it.
    source = re.sub(r"/\*.*?\*/", "", source, flags=re.S)
    source = re.sub(r"^\s*//.*$", "", source, flags=re.M)
    referenced = set(re.findall(r"var\((--[\w-]+)", source))
    tokens_css = TOKENS_CSS.read_text(encoding="utf-8")
    defined = set(re.findall(r"(--[\w-]+)\s*:", tokens_css)) | {f"--{slot}" for slot in SLOTS}
    dangling = sorted(referenced - defined - EXTERNAL_VARS)
    return [
        f"tailwind.config.js reads {name}, which nothing defines — "
        f"utilities using it compute to an invalid value and silently fall back"
        for name in dangling
    ]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if index.css is out of date")
    args = parser.parse_args()

    light, dark = parse_blocks(TOKENS_CSS.read_text(encoding="utf-8"))
    block, failures = render(light, dark)
    failures += check_dangling_vars()

    if failures:
        print("Refusing to generate — the theme is not sound:")
        for failure in failures:
            print(f"  - {failure}")
        return 1

    css = INDEX_CSS.read_text(encoding="utf-8")
    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)

    if not pattern.search(css):
        print(f"error: markers not found in {INDEX_CSS.relative_to(REPO_ROOT)}", file=sys.stderr)
        print("Insert the BEGIN/END marker pair around the theme block first.", file=sys.stderr)
        return 2

    updated = pattern.sub(lambda _: block, css)

    if args.check:
        if updated != css:
            print(f"OUT OF DATE — {INDEX_CSS.relative_to(REPO_ROOT)} does not match the tokens.")
            print("Regenerate with: python3 scripts/gen_shadcn_theme.py")
            return 1
        print(f"OK: {len(SLOTS)} slots match the canonical tokens in both themes.")
        return 0

    INDEX_CSS.write_text(updated, encoding="utf-8")
    print(f"Wrote {len(SLOTS)} slots x 2 themes to {INDEX_CSS.relative_to(REPO_ROOT)}")
    print(f"All {len(SLOT_CONTRAST_CHECKS)} text-on-ground slot pairs clear their floor in both themes.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
