#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2024-2026 Eric Bintner and Halbert Contributors
"""Quarantine CC BY-NC 4.0 (SS64) content out of the shippable macOS corpus.

LEG-CRIT-01 step 1.

`data/macos/support/macos_support.jsonl` mixed two licences in one file: 87
SS64.com command pages under CC BY-NC 4.0 and 17 Halbert-authored guides. Any
paid build — Halbert Pro on LemonSqueezy or the Mac App Store client — that
shipped that file infringed, because "NonCommercial" is judged on the purpose
of the distribution, not on whether the individual file is priced.

This script splits them:

    data/macos/support/macos_support.jsonl   -> Halbert-authored only
    data/non-commercial/macos_ss64/          -> the CC BY-NC 4.0 slice

Every moved record gains explicit `license_spdx` / `license_url` /
`attribution` fields so the record-level gate in
`halbert_core.corpus.license_policy` can catch it wherever it ends up.

Idempotent: re-running on an already-split corpus changes nothing.

Usage:
    python scripts/quarantine_ss64.py [--dry-run] [--data-dir data]
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict, List, Tuple

REPO_ROOT = Path(__file__).resolve().parents[1]

# Record `source` values to quarantine -> licence metadata stamped onto them.
QUARANTINE_SOURCES: Dict[str, Dict[str, str]] = {
    "ss64-macos": {
        "license_spdx": "CC-BY-NC-4.0",
        "license_name": "Creative Commons Attribution-NonCommercial 4.0 International",
        "license_url": "https://creativecommons.org/licenses/by-nc/4.0/",
        "attribution": "SS64.com — Simon Sheppard",
        "commercial_use": "prohibited",
    },
}

SOURCE_FILE = "macos/support/macos_support.jsonl"
QUARANTINE_FILE = "non-commercial/macos_ss64/ss64_macos.jsonl"

QUARANTINE_README = """\
# Non-Commercial Corpus Quarantine

**Do not ship anything in this directory inside a paid or DRM-wrapped build.**

Content here is licensed for **non-commercial use only**. It is kept in the
repository because Halbert's community builds (GPL-3.0, distributed free of
charge) may lawfully use it, and because dropping it outright would lose
provenance for content the corpus was originally built from.

## What lives here

| Path | Upstream | Licence | Attribution |
|------|----------|---------|-------------|
| `macos_ss64/ss64_macos.jsonl` | [SS64.com](https://ss64.com/osx/) | [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/) | SS64.com — Simon Sheppard |

## Which builds may include it

| Channel | Included | Why |
|---------|----------|-----|
| `oss-linux` | ✗ | macOS content; wrong platform |
| `oss-macos` (free, self-distributed, GPL-3.0) | ✗ by default | Permitted by the licence, but excluded so that one corpus serves every macOS channel |
| `macos-pro` (LemonSqueezy, paid) | ✗ **hard block** | Commercial distribution — CC BY-NC forbids it |
| `macos-app-store` (paid channel, DRM) | ✗ **hard block** | Commercial distribution — CC BY-NC forbids it |
| `hf-dataset` (public corpus release) | ✗ | Published separately with its own CC BY-NC 4.0 dataset card |

Enforcement is not a convention — `scripts/corpus_license_gate.py` fails the
build if any of these paths, or any record carrying a quarantined `source`,
reaches a bundle for a channel that cannot carry it. Policy lives in
`config/licensing.yml`.

## Replacement coverage

Nothing is lost by excluding this slice. Every macOS command SS64 documented
has an original, Halbert-authored reference in
`data/macos/support/macos_command_guides.jsonl`, generated by
`scripts/generate_macos_command_guides.py`. The
`macos-command-reference` coverage contract in `config/licensing.yml` is
asserted by `halbert_core/tests/test_corpus_license_gate.py`, so a command can
never quietly drop out of the shippable corpus.

## If you add content here

1. Put it in its own subdirectory with the upstream name.
2. Stamp `license_spdx`, `license_url` and `attribution` on every record.
3. Register the record `source` under `record_quarantine:` in
   `config/licensing.yml`.
4. Add a replacement + coverage contract before anything depends on it.

See `documentation/legal/LEGAL-AND-LICENSING-TODO.md` (LEG-CRIT-01).
"""


def load_jsonl(path: Path) -> List[Dict[str, Any]]:
    records: List[Dict[str, Any]] = []
    if not path.exists():
        return records
    with open(path, "r", encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            records.append(json.loads(line))
    return records


def write_jsonl(path: Path, records: List[Dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        for record in records:
            fh.write(json.dumps(record, ensure_ascii=False) + "\n")


def stamp_license(record: Dict[str, Any], meta: Dict[str, str]) -> Dict[str, Any]:
    """Add explicit licence provenance to a quarantined record."""
    record = dict(record)
    record["license_spdx"] = meta["license_spdx"]
    record["license_url"] = meta["license_url"]
    record["attribution"] = meta["attribution"]
    metadata = dict(record.get("metadata") or {})
    metadata["license_spdx"] = meta["license_spdx"]
    metadata["license_name"] = meta["license_name"]
    metadata["commercial_use"] = meta["commercial_use"]
    metadata["attribution"] = meta["attribution"]
    record["metadata"] = metadata
    return record


def split(records: List[Dict[str, Any]]) -> Tuple[List[Dict[str, Any]], List[Dict[str, Any]]]:
    keep: List[Dict[str, Any]] = []
    quarantine: List[Dict[str, Any]] = []
    for record in records:
        meta = QUARANTINE_SOURCES.get(record.get("source", ""))
        if meta:
            quarantine.append(stamp_license(record, meta))
        else:
            keep.append(record)
    return keep, quarantine


def merge_quarantine(
    existing: List[Dict[str, Any]], incoming: List[Dict[str, Any]]
) -> List[Dict[str, Any]]:
    """Union by record id, newest wins, stable order."""
    by_id: Dict[str, Dict[str, Any]] = {}
    order: List[str] = []
    for record in [*existing, *incoming]:
        rid = str(record.get("id") or record.get("url") or len(order))
        if rid not in by_id:
            order.append(rid)
        by_id[rid] = record
    return [by_id[rid] for rid in order]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--data-dir", default=str(REPO_ROOT / "data"), help="Corpus data directory")
    parser.add_argument("--dry-run", action="store_true", help="Report the split without writing")
    args = parser.parse_args()

    data_dir = Path(args.data_dir)
    source_path = data_dir / SOURCE_FILE
    quarantine_path = data_dir / QUARANTINE_FILE

    if not source_path.exists():
        print(f"error: {source_path} not found", file=sys.stderr)
        return 1

    records = load_jsonl(source_path)
    keep, quarantine = split(records)

    print(f"Read {len(records)} records from {source_path.relative_to(data_dir.parent)}")
    print(f"  keep in place : {len(keep)}")
    print(f"  quarantine    : {len(quarantine)}")

    if not quarantine:
        print("Nothing to quarantine — corpus is already split.")
        # Still make sure the notice exists.
        readme = quarantine_path.parent.parent / "README.md"
        if not readme.exists() and not args.dry_run:
            readme.parent.mkdir(parents=True, exist_ok=True)
            readme.write_text(QUARANTINE_README, encoding="utf-8")
            print(f"  wrote {readme}")
        return 0

    if args.dry_run:
        by_source: Dict[str, int] = {}
        for record in quarantine:
            by_source[record.get("source", "?")] = by_source.get(record.get("source", "?"), 0) + 1
        for src, count in sorted(by_source.items()):
            print(f"    {src}: {count} -> {quarantine_path.relative_to(data_dir.parent)}")
        print("(dry run — nothing written)")
        return 0

    merged = merge_quarantine(load_jsonl(quarantine_path), quarantine)
    write_jsonl(quarantine_path, merged)
    write_jsonl(source_path, keep)

    readme = quarantine_path.parent.parent / "README.md"
    readme.write_text(QUARANTINE_README, encoding="utf-8")

    print(f"\nWrote {len(merged)} records -> {quarantine_path.relative_to(data_dir.parent)}")
    print(f"Wrote {len(keep)} records -> {source_path.relative_to(data_dir.parent)}")
    print(f"Wrote {readme.relative_to(data_dir.parent)}")
    print("\nNext: regenerate replacement coverage and run the gate:")
    print("  python scripts/generate_macos_command_guides.py")
    print("  python scripts/corpus_license_gate.py --channel macos-pro --channel macos-app-store")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
